name: Windows - LiteManager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 60

steps:
  - name: Downloading & Installing Essentials
    run: |
      $url = "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/Downloads.bata"
      $outFile = "Downloads.bat"
      $expectedHash = "YOUR_EXPECTED_SHA256_HASH"  # Replace with actual hash

      # Download file securely
      Invoke-WebRequest -Uri $url -OutFile $outFile -UseBasicParsing

      # Verify file integrity
      $hash = Get-FileHash -Path $outFile -Algorithm SHA256
      if ($hash.Hash -ne $expectedHash) {
        throw "File tampering detected!"
      }

      # Run downloaded script with secure command invocation
      cmd /c $outFile

  - name: Connect to LiteManager
    run: |
      # Use secure command invocation
      cmd /c show.bat

  - name: Time Counter
    run: |
      # Use secure command invocation
      cmd /c loop.bat
