name: Windows - LiteManager
on:
  workflow_dispatch:
jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 60  # Reduced timeout to prevent abuse

steps:
  - name: Downloading & Installing Essentials
    run: |
      $url = "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/Downloads.bat"
      $outFile = "Downloads.bat"
      Invoke-WebRequest -Uri $url -OutFile $outFile
      # Verify file integrity (optional)
      # $hash = Get-FileHash -Path $outFile -Algorithm SHA256
      # if ($hash.Hash -ne "expected_hash") { throw "File tampering detected!" }
      cmd /c $outFile

  - name: Connect to LiteManager
    run: |
      # Use secure command invocation
      cmd /c show.bat

  - name: Time Counter
    run: |
      # Use secure command invocation
      cmd /c loop.bat

  # Additional security steps
  - name: Cleanup
    run: |
      # Remove downloaded files
      Remove-Item -Path Downloads.bat, show.bat, loop.bat
